### ISSUE TITLE
InvalidDescriptionException: Invalid plugin.yml

### ISSUE THREAD

**Issue by glob03** [Banjo-226/bottom-line#1]
[14:42:56] [Server thread/INFO]: Using epoll channel type
[14:42:56] [Server thread/ERROR]: Could not load 'plugins/BottomLine.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-12698ea]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.8.8.jar:git-Spigot-5f38d38-12698ea]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-5f38d38-12698ea]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-5f38d38-12698ea]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-5f38d38-12698ea]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
    ... 6 more
[14:42:56] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[14:42:56] [Server thread/INFO]: [CleanroomGenerator] Loading CleanroomGenerator v1.0.0

sorry but it doesn't mean anything to me

**Comment by Banjo-226** [comment]
Fixed the issue, thanks
