### ISSUE TITLE
Got failure by creating and warppoint

### ISSUE THREAD

**Issue by Endstille2013** [Banjo-226/bottom-line#10]
Got failure by creating and warppoint on my server.
Server-consol with the failure:

[09:56:53 INFO]: Endstille_ issued server command: /warputil create thehouse
[09:56:53 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'warputil' in plugin BottomLine v1.2.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchFieldError: ENTITY_PLAYER_LEVELUP
        at com.Banjo226.util.Util.playSound(Util.java:99) ~[?:?]
        at com.Banjo226.commands.teleportation.warp.WarpUtil.run(WarpUtil.java:40) ~[?:?]
        at com.Banjo226.manager.CommandManager.onCommand(CommandManager.java:145) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot_hn_ml.jar:git-Spigot-e4d4710-e1ebe52]
        ... 15 more

**Comment by Banjo-226** [comment]
Fixed :)
