### ISSUE TITLE
ban system

### ISSUE THREAD

**Issue by Walkomine** [Banjo-226/bottom-line#8]
Hey, I'm using this plugin on my server at the version 1.12. Everything works fine except the ban. I can't ban anyone every time there's an error message. Can u fix this please?

**Comment by Banjo-226** [comment]
Could you please send the error message from console to here so then I could have a look? I have come across no issues when testing, so it would be helpful if you could send me the stack trace  :)

**Comment by Adamisboxed** [comment]
This is what I'm seeing when I do a ban or temp ban

01.11 11:32:53 [Server] INFO ... 15 more
01.11 11:32:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at com.Banjo226.manager.CommandManager.onCommand(CommandManager.java:145) ~[?:?]
01.11 11:32:53 [Server] INFO at com.Banjo226.commands.law.ban.Ban.run(Ban.java:57) ~[?:?]
01.11 11:32:53 [Server] INFO at com.Banjo226.util.files.PlayerData.setOfflineBanned(PlayerData.java:208) ~[?:?]
01.11 11:32:53 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.OfflinePlayer.setBanned(Z)V
01.11 11:32:53 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
01.11 11:32:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
01.11 11:32:53 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
01.11 11:32:53 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.11 11:32:53 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ban' in plugin BottomLine v1.2.10
01.11 11:32:53 [Server] ERROR null
